x=input("enter the value:")
y=input("enter the value:")
sum1=int(x)+int(y)
print("sum1",sum1) 
sum2=int(x)-int(y)
print("sum1",sum2) 
sum3=int(x)*int(y)
print("sum1",sum3) 
sum4=int(x)/int(y)
print("sum1",sum4) 
sum5=int(x)%int(y)
print("sum1",sum5) 
