x1=int(input("enter the value of x1 :"))
x2=int(input("enter the value of x2 :"))
y1=int(input("enter the value of y1 :"))
y2=int(input("enter the value of y2 :"))
slope=float(y2-y1)/(x2-x1)
print("slope is:")
print(slope)
