P=int(input("enter the value of P :"))
R=int(input("enter the value of R :"))
N=int(input("enter the value of N :"))
T=int(input("enter the value of T :"))
CI=P*(1+(R/(100*N)))**(N*T)
print("COMPOUND INTEREST:")
print(CI)