a= ['003' ,'tarni','bardoli']
print(a)
a.append('computer')
print(a)
a.append('palsana')
print(a)
a.append('686')
print(a)
a.insert(3,'8780345459')
print(a)
a.remove('686')
print(a)
a.reverse()
print(a)
del a[1:3]
print(a)
